(()=>{'use strict';
const SHEET='1vA4ALaNS7Zzmreb69lO7c04d4bb8k2chWaQFKOx5eUU',GID='0',REFRESH=300000;
const GREEN=['#cbd9c9','#9fba9e','#73936f','#456d4e','#123f2c'],NONE='#eadfbe';
const alias={'usa':'united states of america','us':'united states of america','united states':'united states of america','america':'united states of america','uk':'united kingdom','great britain':'united kingdom','britain':'united kingdom','russian federation':'russia','republic of korea':'south korea','korea south':'south korea','viet nam':'vietnam','tanzania united republic of':'tanzania','cote d ivoire':'ivory coast','côte d ivoire':'ivory coast','dem rep congo':'democratic republic of the congo','central african rep':'central african republic','dominican rep':'dominican republic','eq guinea':'equatorial guinea','bosnia and herz':'bosnia and herzegovina','w sahara':'western sahara','s sudan':'south sudan','solomon is':'solomon islands','fr s antarctic lands':'french southern territories','falkland is':'falkland islands','north korea':'north korea'};
const iso={"004":"AF","008":"AL","010":"AQ","012":"DZ","016":"AS","020":"AD","024":"AO","028":"AG","031":"AZ","032":"AR","036":"AU","040":"AT","044":"BS","048":"BH","050":"BD","051":"AM","052":"BB","056":"BE","060":"BM","064":"BT","068":"BO","070":"BA","072":"BW","074":"BV","076":"BR","084":"BZ","086":"IO","090":"SB","092":"VG","096":"BN","100":"BG","104":"MM","108":"BI","112":"BY","116":"KH","120":"CM","124":"CA","132":"CV","136":"KY","140":"CF","144":"LK","148":"TD","152":"CL","156":"CN","158":"TW","162":"CX","166":"CC","170":"CO","174":"KM","175":"YT","178":"CG","180":"CD","184":"CK","188":"CR","191":"HR","192":"CU","196":"CY","203":"CZ","204":"BJ","208":"DK","212":"DM","214":"DO","218":"EC","222":"SV","226":"GQ","231":"ET","232":"ER","233":"EE","234":"FO","238":"FK","239":"GS","242":"FJ","246":"FI","248":"AX","250":"FR","254":"GF","258":"PF","260":"TF","262":"DJ","266":"GA","268":"GE","270":"GM","275":"PS","276":"DE","288":"GH","292":"GI","296":"KI","300":"GR","304":"GL","308":"GD","312":"GP","316":"GU","320":"GT","324":"GN","328":"GY","332":"HT","334":"HM","336":"VA","340":"HN","344":"HK","348":"HU","352":"IS","356":"IN","360":"ID","364":"IR","368":"IQ","372":"IE","376":"IL","380":"IT","384":"CI","388":"JM","392":"JP","398":"KZ","400":"JO","404":"KE","408":"KP","410":"KR","414":"KW","417":"KG","418":"LA","422":"LB","426":"LS","428":"LV","430":"LR","434":"LY","438":"LI","440":"LT","442":"LU","446":"MO","450":"MG","454":"MW","458":"MY","462":"MV","466":"ML","470":"MT","474":"MQ","478":"MR","480":"MU","484":"MX","492":"MC","496":"MN","498":"MD","499":"ME","500":"MS","504":"MA","508":"MZ","512":"OM","516":"NA","520":"NR","524":"NP","528":"NL","531":"CW","533":"AW","534":"SX","535":"BQ","540":"NC","548":"VU","554":"NZ","558":"NI","562":"NE","566":"NG","570":"NU","574":"NF","578":"NO","580":"MP","581":"UM","583":"FM","584":"MH","585":"PW","586":"PK","591":"PA","598":"PG","600":"PY","604":"PE","608":"PH","612":"PN","616":"PL","620":"PT","624":"GW","626":"TL","630":"PR","634":"QA","638":"RE","642":"RO","643":"RU","646":"RW","652":"BL","654":"SH","659":"KN","660":"AI","662":"LC","663":"MF","666":"PM","670":"VC","674":"SM","678":"ST","682":"SA","686":"SN","688":"RS","690":"SC","694":"SL","702":"SG","703":"SK","704":"VN","705":"SI","706":"SO","710":"ZA","716":"ZW","724":"ES","728":"SS","729":"SD","732":"EH","740":"SR","744":"SJ","748":"SZ","752":"SE","756":"CH","760":"SY","762":"TJ","764":"TH","768":"TG","772":"TK","776":"TO","780":"TT","784":"AE","788":"TN","792":"TR","795":"TM","796":"TC","798":"TV","800":"UG","804":"UA","807":"MK","818":"EG","826":"GB","831":"GG","832":"JE","833":"IM","834":"TZ","840":"US","850":"VI","854":"BF","858":"UY","860":"UZ","862":"VE","876":"WF","882":"WS","887":"YE","894":"ZM"};
const $=id=>document.getElementById(id),els={svg:$('world'),layer:$('zoomLayer'),sphere:$('sphere'),outline:$('outline'),grid:$('graticule'),countries:$('countries'),legend:$('legend'),summary:$('summary'),status:$('status'),statusText:$('statusText'),loading:$('loading'),tooltip:$('tooltip'),tooltipBody:$('tooltipBody'),sheet:$('sheet'),sheetBody:$('sheetBody'),backdrop:$('backdrop')};
let features=[],paths=null,books=new Map(),bins=[],zoom,active=null,pinned=false,lastCheck=0,hoverTimer=null;
const norm=v=>{const n=String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/&/g,' and ').replace(/[^a-z0-9]+/g,' ').trim();return alias[n]||n};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const flag=id=>{const c=iso[String(id).padStart(3,'0')];return c?String.fromCodePoint(...c.split('').map(x=>127397+x.charCodeAt())):'🗺️'};
function status(t,state='live'){els.statusText.textContent=t;els.status.dataset.state=state}
function group(rows){books=new Map();for(const r of rows){if(!r.Title||!r.Country)continue;const k=norm(r.Country);if(!books.has(k))books.set(k,[]);books.get(k).push({title:String(r.Title).trim(),author:String(r.Author||'Unknown author').trim()})}for(const list of books.values())list.sort((a,b)=>a.title.localeCompare(b.title,'en',{sensitivity:'base'}));buildScale();paint();const total=[...books.values()].reduce((n,a)=>n+a.length,0);els.summary.textContent=`${total.toLocaleString('en-GB')} books across ${books.size.toLocaleString('en-GB')} countries`}
function buildScale(){const max=Math.max(1,...[...books.values()].map(a=>a.length));let prev=0;bins=[];for(let i=1;i<=5;i++){let top=i===5?max:Math.max(prev+1,Math.round(Math.expm1(Math.log1p(max)*i/5)));top=Math.min(max,top);if(top>prev)bins.push({min:prev+1,max:top,color:GREEN[GREEN.length-(5-i)-1]||GREEN[i-1]});prev=top;if(top>=max)break}const palette=GREEN.slice(GREEN.length-bins.length);bins=bins.map((b,i)=>({...b,color:palette[i]}));els.legend.innerHTML=`<div class="legend-row"><i class="swatch" style="background:${NONE}"></i><span>0</span></div>`+bins.map(b=>`<div class="legend-row"><i class="swatch" style="background:${b.color}"></i><span>${b.min===b.max?b.min:`${b.min}–${b.max}`}</span></div>`).join('')}
function colour(n){if(!n)return NONE;return (bins.find(b=>n<=b.max)||bins[bins.length-1]).color}
function paint(){if(!paths)return;paths.attr('fill',d=>colour((books.get(norm(d.properties.name))||[]).length)).attr('aria-label',d=>{const n=(books.get(norm(d.properties.name))||[]).length;return `${d.properties.name}: ${n} ${n===1?'book':'books'}`})}
function card(d){const list=books.get(norm(d.properties.name))||[],name=d.properties.name,count=list.length;return `<article class="country-card"><header class="country-top"><div class="country-title"><span class="flag">${flag(d.id)}</span><h3 id="sheetName">${esc(name)}</h3></div><p class="count">${count.toLocaleString('en-GB')} ${count===1?'book':'books'} read</p></header>${count?`<ol class="book-list">${list.map(b=>`<li><strong>${esc(b.title)}</strong><span>${esc(b.author)}</span></li>`).join('')}</ol>`:`<p class="empty">No books recorded from this country yet.</p>`}</article>`}
function clearActive(){if(active)d3.select(active).classed('active',false);active=null}
function touchLayout(){return matchMedia('(hover:none)').matches||matchMedia('(max-width:900px)').matches}
function openTip(event,d,pin=false){clearTimeout(hoverTimer);if(touchLayout()){openSheet(d);return}clearActive();active=event.currentTarget;d3.select(active).classed('active',true);pinned=pin;els.tooltipBody.innerHTML=card(d);els.tooltip.hidden=false;place(event.clientX,event.clientY)}
function place(x,y){const r=els.tooltip.getBoundingClientRect(),pad=14;let left=x+18,top=y+18;if(left+r.width>innerWidth-pad)left=x-r.width-18;if(top+r.height>innerHeight-pad)top=innerHeight-r.height-pad;els.tooltip.style.left=`${Math.max(pad,left)}px`;els.tooltip.style.top=`${Math.max(pad,top)}px`}
function closeTip(){clearTimeout(hoverTimer);els.tooltip.hidden=true;pinned=false;clearActive()}
function scheduleTipClose(){clearTimeout(hoverTimer);hoverTimer=setTimeout(()=>{if(!pinned)closeTip()},140)}
function openSheet(d){clearActive();els.sheetBody.innerHTML=card(d);els.sheet.hidden=false;els.backdrop.hidden=false;document.body.style.overflow='hidden'}
function closeSheet(){els.sheet.hidden=true;els.backdrop.hidden=true;document.body.style.overflow='';clearActive()}
async function buildMap(){if(!window.d3||!window.topojson)throw new Error('Mapping libraries did not load');const world=await d3.json('https://cdn.jsdelivr.net/npm/world-atlas@2.0.2/countries-110m.json');features=topojson.feature(world,world.objects.countries).features.filter(d=>d.properties&&d.properties.name!=='Antarctica');const projection=d3.geoRobinson().fitExtent([[28,28],[1172,622]],{type:'Sphere'}),path=d3.geoPath(projection),svg=d3.select(els.svg);els.sphere.setAttribute('d',path({type:'Sphere'}));els.outline.setAttribute('d',path({type:'Sphere'}));els.grid.setAttribute('d',path(d3.geoGraticule10()));paths=d3.select(els.countries).selectAll('path').data(features).join('path').attr('class','country').attr('d',path).attr('tabindex',0).attr('role','button').on('pointerenter',function(e,d){if(!pinned)openTip(e,d)}).on('pointermove',function(e){if(!pinned&&!els.tooltip.hidden)place(e.clientX,e.clientY)}).on('pointerleave',()=>{if(!pinned)scheduleTipClose()}).on('click',function(e,d){e.stopPropagation();openTip(e,d,true)}).on('keydown',function(e,d){if(e.key==='Enter'||e.key===' '){e.preventDefault();openTip(e,d,true)}});zoom=d3.zoom().scaleExtent([1,9]).translateExtent([[-300,-200],[1500,850]]).on('zoom',e=>d3.select(els.layer).attr('transform',e.transform));svg.call(zoom).on('dblclick.zoom',null).on('click',e=>{if(e.target===els.svg)closeTip()});paint();els.loading.classList.add('done')}
function reset(){d3.select(els.svg).transition().duration(450).call(zoom.transform,d3.zoomIdentity);closeTip();closeSheet()}
function parse(payload){if(!payload||payload.status!=='ok'||!payload.table)throw new Error('Invalid sheet response');const heads=payload.table.cols.map((c,i)=>(c.label||c.id||String(i)).trim());return payload.table.rows.map(row=>{const o={};heads.forEach((h,i)=>{const c=row.c?.[i];o[h]=c?(c.f??c.v??''):''});return{Title:o.Title??o.A??'',Author:o.Author??o.B??'',Genre:o.Genre??o.C??'',Gender:o.Gender??o.D??'',Country:o.Country??o.E??''}})}
function sheet(){return new Promise((resolve,reject)=>{const cb=`__atlas_${Date.now()}_${Math.random().toString(36).slice(2)}`,s=document.createElement('script');let done=false,t;const finish=fn=>v=>{if(done)return;done=true;clearTimeout(t);delete window[cb];s.remove();fn(v)};window[cb]=finish(p=>{try{resolve(parse(p))}catch(e){reject(e)}});s.onerror=finish(()=>reject(new Error('Sheet unavailable')));const tqx=encodeURIComponent(`out:json;responseHandler:${cb}`),q=encodeURIComponent('select A,B,C,D,E where A is not null');s.src=`https://docs.google.com/spreadsheets/d/${SHEET}/gviz/tq?gid=${GID}&headers=1&tqx=${tqx}&tq=${q}&_=${Date.now()}`;document.head.appendChild(s);t=setTimeout(finish(()=>reject(new Error('Sheet timed out'))),12000)})}
async function refresh({quiet=false}={}){if(!quiet)status('Checking the live reading ledger…','loading');try{const rows=await sheet();group(rows);lastCheck=Date.now();const time=new Intl.DateTimeFormat('en-GB',{hour:'2-digit',minute:'2-digit'}).format(new Date());status(`Live sheet · checked ${time}`,'live')}catch(e){console.warn(e);if(window.ATLAS_SNAPSHOT?.rows?.length){group(window.ATLAS_SNAPSHOT.rows);status('Saved snapshot · live refresh unavailable','fallback')}else status('Reading ledger unavailable','fallback')}}
els.tooltip.addEventListener('pointerenter',()=>clearTimeout(hoverTimer));els.tooltip.addEventListener('pointerleave',()=>{if(!pinned)scheduleTipClose()});
$('zoomIn').onclick=()=>d3.select(els.svg).transition().call(zoom.scaleBy,1.45);$('zoomOut').onclick=()=>d3.select(els.svg).transition().call(zoom.scaleBy,1/1.45);$('reset').onclick=$('logoReset').onclick=reset;$('tooltipClose').onclick=closeTip;$('sheetClose').onclick=$('backdrop').onclick=closeSheet;addEventListener('keydown',e=>{if(e.key==='Escape'){closeTip();closeSheet()}});
(async()=>{try{if(window.ATLAS_SNAPSHOT?.rows)group(window.ATLAS_SNAPSHOT.rows);await buildMap();await refresh();setInterval(()=>refresh({quiet:true}),REFRESH);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&Date.now()-lastCheck>=REFRESH)refresh({quiet:true})})}catch(e){console.error(e);els.loading.innerHTML='<strong>The atlas could not be unrolled.</strong><span>Please reload the page.</span>';status('Atlas unavailable','fallback')}})();
})();
